name: flutter_timer
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.0
  dio_cache_interceptor: ^3.4.4
  dio_cache_interceptor_hive_store: ^3.2.1
  intl: ^0.18.1
  bloc: ^8.1.2
  hydrated_bloc: ^9.1.3
  flutter_bloc: ^8.1.3
  noodle_image: ^1.0.2
  path_provider: ^2.1.2
  stark: ^4.0.0
  uuid: ^4.3.3
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: OdooIcons
      fonts:
        - asset: assets/icons/odoo_icons.ttf